
[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

bytecode_hash = "none"

# Enable fuzz testing settings
[fuzz]
runs = 256

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
quote_style = "double"
number_underscore = "thousands"

# Profile for CI or production builds
[profile.ci]
optimizer = true
optimizer_runs = 200
verbosity = 3
